# Generated by Django 4.2.7 on 2023-11-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_shoppingcart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзина"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.RenameField(
            model_name="subcategory",
            old_name="parent_category",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
