# Generated by Django 4.2.7 on 2023-11-30 10:50

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image1",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите Категорию перед выбор Подкатегорий",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.ImageField(blank=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.ImageField(blank=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена указывается в Int или Float",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="category",
                chained_model_field="category",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
    ]
